package ng.com.mtn.oim;

import oracle.jbo.server.ApplicationModuleImpl;
import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Dec 21 10:12:36 PST 2022
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class BulkAppModuleImpl extends ApplicationModuleImpl{
    /**
     * This is the default constructor (do not remove).
     */
    public BulkAppModuleImpl() {
    }

    /**
     * Container's getter for HREmpVO1.
     * @return HREmpVO1
     */
    public ViewObjectImpl getHREmpVO1(){
        return (ViewObjectImpl)findViewObject("HREmpVO1");
    }

}
