<wsdl:definitions
     name="updateHR_EMP"
     targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/DemoManagerApproval/DemoBulkApproval/updateHR_EMP"
     xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/DemoManagerApproval/DemoBulkApproval/updateHR_EMP"
     xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/"
     xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
     xmlns:db="http://xmlns.oracle.com/pcbpel/adapter/db/updateHR_EMP"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    >
  <plt:partnerLinkType name="updateHR_EMP_plt" >
    <plt:role name="updateHR_EMP_role" >
      <plt:portType name="tns:updateHR_EMP_ptt" />
    </plt:role>
  </plt:partnerLinkType>
  <plt:partnerLinkType name="updateHR_EMP_plt" >
    <plt:role name="updateHR_EMP_role" >
      <plt:portType name="tns:updateHR_EMP_ptt" />
    </plt:role>
  </plt:partnerLinkType>
  <plt:partnerLinkType name="updateHR_EMP_plt" >
    <plt:role name="updateHR_EMP_role" >
      <plt:portType name="tns:updateHR_EMP_ptt" />
    </plt:role>
  </plt:partnerLinkType>
  <plt:partnerLinkType name="updateHR_EMP_plt" >
    <plt:role name="updateHR_EMP_role" >
      <plt:portType name="tns:updateHR_EMP_ptt" />
    </plt:role>
  </plt:partnerLinkType>
  <plt:partnerLinkType name="updateHR_EMP_plt" >
    <plt:role name="updateHR_EMP_role" >
      <plt:portType name="tns:updateHR_EMP_ptt" />
    </plt:role>
  </plt:partnerLinkType>
  <plt:partnerLinkType name="updateHR_EMP_plt" >
    <plt:role name="updateHR_EMP_role" >
      <plt:portType name="tns:updateHR_EMP_ptt" />
    </plt:role>
  </plt:partnerLinkType>
  <plt:partnerLinkType name="updateHR_EMP_plt" >
    <plt:role name="updateHR_EMP_role" >
      <plt:portType name="tns:updateHR_EMP_ptt" />
    </plt:role>
  </plt:partnerLinkType>
  <plt:partnerLinkType name="updateHR_EMP_plt" >
    <plt:role name="updateHR_EMP_role" >
      <plt:portType name="tns:updateHR_EMP_ptt" />
    </plt:role>
  </plt:partnerLinkType>
    <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema" >
        <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/updateHR_EMP" schemaLocation="../Schemas/updateHR_EMP.xsd" />
      </schema>
      <schema xmlns="http://www.w3.org/2001/XMLSchema" >
        <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/updateHR_EMP" schemaLocation="../Schemas/updateHR_EMP.xsd" />
      </schema>
      <schema xmlns="http://www.w3.org/2001/XMLSchema" >
        <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/updateHR_EMP" schemaLocation="../Schemas/updateHR_EMP.xsd" />
      </schema>
      <schema xmlns="http://www.w3.org/2001/XMLSchema" >
        <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/updateHR_EMP" schemaLocation="../Schemas/updateHR_EMP.xsd" />
      </schema>
      <schema xmlns="http://www.w3.org/2001/XMLSchema" >
        <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/updateHR_EMP" schemaLocation="../Schemas/updateHR_EMP.xsd" />
      </schema>
      <schema xmlns="http://www.w3.org/2001/XMLSchema" >
        <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/updateHR_EMP" schemaLocation="../Schemas/updateHR_EMP.xsd" />
      </schema>
      <schema xmlns="http://www.w3.org/2001/XMLSchema" >
        <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/updateHR_EMP" schemaLocation="../Schemas/updateHR_EMP.xsd" />
      </schema>
      <schema xmlns="http://www.w3.org/2001/XMLSchema" >
        <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/updateHR_EMP" schemaLocation="../Schemas/updateHR_EMP.xsd" />
      </schema>
    </wsdl:types>
    <wsdl:message name="updateHR_EMPInput_msg">
        <wsdl:part name="updateHR_EMPInput_msg" element="db:updateHR_EMPInput"/>
    </wsdl:message>
    <wsdl:portType name="updateHR_EMP_ptt">
        <wsdl:operation name="updateHR_EMP">
            <wsdl:input message="tns:updateHR_EMPInput_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>
